# -*- coding: utf-8 -*-
"""Copy of Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VlkTK5BILZAS9GYdks_gbg1tR065PA6H
"""

!pip install ultralytics
from ultralytics import YOLO

# Commented out IPython magic to ensure Python compatibility.
# %%writefile fashion.yaml
# 
# ---
# train: /content/drive/MyDrive/dataset/train_2/images
# val: /content/drive/MyDrive/dataset/val_2/images
# test: /content/drive/MyDrive/dataset/test_2/images
# nc: 4
# names:
#   "0": other
#   "1": upper
#   "2": lower
#   "3": full

EPOCHS = 50
IMG_SIZE = 640
BATCH = 32

# to train the model

model = YOLO('yolov8n.pt')

results = model.train(
    data = 'fashion.yaml',
    imgsz = IMG_SIZE,
    epochs = EPOCHS,
    batch = BATCH,
    name = 'yolov8n_v8',
    pretrained = True,
    optimizer = 'Adam'
)

# to validate the model

model = YOLO('yolov8n.pt')
model = YOLO('/content/runs/detect/yolov8n_v8/weights/best.pt')
results = model.val(
    data = 'fashion.yaml',
    imgsz = IMG_SIZE,
    epochs = EPOCHS,
    batch = BATCH,
)

import zipfile
import os

folder_to_zip = '/content/runs'
zip_file_path = '/content/runs.zip'

with zipfile.ZipFile(zip_file_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, _, files in os.walk(folder_to_zip):
        for file in files:
            file_path = os.path.join(root, file)
            arcname = os.path.relpath(file_path, folder_to_zip)
            zipf.write(file_path, arcname)

print(f"ZIP archive created at: {zip_file_path}")

import locale
locale.getpreferredencoding = lambda: "UTF-8"
from google.colab import files
!cp runs.zip "/content/drive/MyDrive/"

# save best weights

model = YOLO('yolov8n.pt')  # load an official model
model = YOLO('/content/runs/detect/yolov8n_v8/weights/best.pt')  # load a custom trained

# Export the model
model.export(format='onnx')





